
CREATE TABLE GROUPE_POLICY
	(
	POLICY_ID   VARCHAR2 (20) NOT NULL,
	POLICY_TYPE VARCHAR2 (20) NOT NULL,
	POLICY_COMMDATE VARCHAR2(25) NOT NULL,
	POLICY_ENDDATE  VARCHAR2(25) NOT NULL,
	PAYMENT_MODE    VARCHAR2 (20) NOT NULL,
	PAYMENT_FREQ    VARCHAR2 (20) NOT NULL,
	PREMIUM_AMOUNT  NUMBER (10) NOT NULL,
	
	PRIMARY KEY (POLICY_ID)
	);
	
	
CREATE TABLE GROUPE_HEALTHPOLICY
	(
	POLICY_REFNUM   VARCHAR2 (20) NOT NULL,
	POLICY_ID       VARCHAR2 (20) NOT NULL,
	CUST_ID         NUMBER (10) NOT NULL,
	POLICY_TENURE   NUMBER (5) NOT NULL,
	
	CONSTRAINT MYPRIMARY    PRIMARY KEY (POLICY_REFNUM),
   
	FOREIGN KEY (POLICY_ID) REFERENCES GROUPE_POLICY(POLICY_ID),
	FOREIGN KEY (CUST_ID)   REFERENCES GROUPE_CUSTOMER(CUST_ID)
	);
	
	
	
	SELECT CUSTOMERPOLICY_SEQ.NEXTVAL FROM DUAL
	
CREATE TABLE GROUPE_VEHICLEPOLICY
	(
	POLICY_REFNUM   VARCHAR2 (20) NOT NULL,
	POLICY_ID       VARCHAR2 (20) NOT NULL,
	CUST_ID         NUMBER (10) NOT NULL,
	
  
	VEHICLE_NUM     VARCHAR2 (20) NOT NULL,
	LICENCE_NUM     VARCHAR2 (20) NOT NULL,
	VEHICLE_TYPE    VARCHAR2 (25) NOT NULL,
	
	CONSTRAINT MYPRIMARY1 PRIMARY KEY (POLICY_REFNUM),
	FOREIGN KEY (POLICY_ID) REFERENCES GROUPE_POLICY (POLICY_ID),
	FOREIGN KEY (CUST_ID) REFERENCES GROUPE_CUSTOMER (CUST_ID)
	);
	DROP SEQUENCE JA41E.CUSTOMERPOLICY_SEQ;

CREATE SEQUENCE JA41E.CUSTOMERPOLICY_SEQ
	START WITH 21
	INCREMENT BY 1
	NOMINVALUE
	MAXVALUE 9999999999999999999999999999
	NOCYCLE
	NOORDER
	CACHE 20;

SELECT 'H'||to_char(CUSTOMERPOLICY_SEQ.NEXTVAL,'FM0000')from dual

INSERT INTO GROUPE_CUSTOMERPOLICY VALUES(CUSTOMERPOLICY_SEQ.NEXTVAL,'102',1,'09/11/2014','07/12/2014','creditcard','monthly',50000,1);
DELETE FROM GROUPE_CUSTOMERPOLICY WHERE CUST_ID=1;