CREATE TABLE GROUPE_CUSTOMER (  

CUST_ID NUMBER(10) PRIMARY KEY,
CUST_NAME VARCHAR2(25) NOT NULL ,
CUST_DOB VARCHAR2(25) NOT NULL ,
CUST_EMAIL VARCHAR2(25) NOT NULL ,
CUST_ADDRESS VARCHAR2(25) NOT NULL ,
CUST_CONTACTNUM NUMBER(12) NOT NULL ,
PHOTO_PROOF  VARCHAR2(25) NOT NULL ,
PHOTO_PROOF_ID  VARCHAR2(25) NOT NULL, 
ADDRESS_PROOF  VARCHAR2(25) NOT NULL ,
ADDRESS_PROOF_ID  VARCHAR2(25) NOT NULL, 
CUST_REGDATE VARCHAR2(20) NOT NULL
);
 
 
UPDATE GROUPE_CUSTOMER SET CUST_NAME='dasdasd',CUST_DOB='07/11/1992', CUST_EMAIL='asdasd', CUST_ADDRESS='asdasd', CUST_CONTACTNUM=322  WHERE CUST_ID=20

SELECT * FROM GROUPE_CUSTOMER


CREATE TABLE GROUPE_EMPLOYEE
(
EMP_ID VARCHAR2(10),
EMP_PASS VARCHAR2(15)

)



SELECT COUNT(POLICY_REFNUM) AS COUNT FROM GROUPE_CUSTOMERPOLICY WHERE CUST_ID=1 


SELECT COUNT(GROUPE_VEHICLEPOLICY.POLICY_REFNUM) AS COUNT FROM GROUPE_VEHICLEPOLICY,GROUPE_CUSTOMERPOLICY 
WHERE GROUPE_VEHICLEPOLICY.POLICY_REFNUM=GROUPE_CUSTOMERPOLICY.POLICY_REFNUM AND CUST_ID=10


SELECT COUNT(GROUPE_VEHICLEPOLICY.POLICY_REFNUM) AS COUNT FROM GROUPE_VEHICLEPOLICY,GROUPE_CUSTOMERPOLICY WHERE GROUPE_VEHICLEPOLICY.POLICY_REFNUM=GROUPE_CUSTOMERPOLICY.POLICY_REFNUM AND CUST_ID=10








SELECT * FROM GROUPE_CUSTOMER 


INSERT INTO GROUPE_CUSTOMER VALUES(1,'A','A','A','A',222222,'A','A','A','A',0,0,'SDDSS')   
 
SELECT GROUPE_SEQ_CUSTOMER.NEXTVAL FROM DUAL

SELECT GROUPE_SEQ_CUSTOMER.CURRVAL AS ID FROM DUAL


SE

ALTER TABLE GROUPE_CUSTOMER DROP COLUMN HEALTH_POLICY_STATUS;
ALTER TABLE GROUPE_CUSTOMER DROP COLUMN VEHICLE_POLICY_STATUS

CREATE SEQUENCE GROUPE_SEQ_CUSTOMER	
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;


DELETE FROM GROUPE_CUSTOMER WHERE CUST_ID=23

INSERT INTO GROUPE_CUSTOMER VALUES(GROUPE_SEQ_CUSTOMER.NEXTVAL,'A','A','A','A',2222,'A','A','A','A',0,0)


SELECT CUST_EMAIL AS EMAIL FROM GROUPE_CUSTOMER 